#!/usr/bin/env php
<?

define(CREOVEL_PATH, dirname(dirname(__FILE__))."/vendor/creovel/");

echo "Freezing Creovel to the Newest Version ...\n";

// Remove Old and Check Out Newest Version
exec("rm -Rfv ".CREOVEL_PATH);
echo exec("/usr/bin/env svn export http://creovel.googlecode.com/svn/trunk/vendor/creovel/ ".CREOVEL_PATH)."\n";

echo "Creovel Successfully Updated!\n";

?>
