#!/usr/bin/php
<?

// Found and Converted to PHP
// http://www.webtypes.com/files/bc-post-commit.rb
// Thanks Guys!

require_once dirname(__FILE__).'/../config/environment.php';
require_once dirname(__FILE__).'/../lib/subversion.php';

$subversion = new Subversion(LOCAL_REPOSITORY_PATH, BROWSE_REPOSITORY_PATH, SVNLOOK_PATH);

$model = new model();
$model->_action_query->query('DELETE FROM changesets');

for ($i = 1; $i <= $subversion->youngest(); $i++)
{ 
	echo "Importing Revision {$i}\n";
	$subversion->import($i);
}

?>
