#!/usr/bin/php
<?

require_once dirname(__FILE__).'/../config/environment.php';
require_once dirname(__FILE__).'/../lib/subversion.php';

$subversion = new Subversion(LOCAL_REPOSITORY_PATH, BROWSE_REPOSITORY_PATH, SVNLOOK_PATH);
$subversion->import($subversion->youngest());

?>
